author: computerdude5000
database: false
description: buy McMMO exp points!
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.github.computerdude5000.m2exp.M2EXP
name: M2EXP
startup: postworld
version: 0.1.0
depend: [Vault, mcMMO]
commands:
 bacrobatics:
   description: buy McMMO Acrobatics skill experience points
 barchery:
   description: buy McMMO Archery skill experience points
 baxes: 
   description: buy McMMO Axes skill experience points
 bexcavation: 
   description: buy McMMO excavation skill experience points
 bfishing:
   description: buy McMMO Fishing skill experience points
 bherbalism:
   description: buy McMMO Herbalism skill experience points
 bmining:
   description: buy McMMO Mining skill experience points
 brepair:
   description: buy McMMO Repair skill experience points
 bswords:
   description: buy McMMO Swords skill experience points
 btaming:
   description: buy McMMO Taming skill experience points
 bunarmed:
   description: buy McMMO Unarmed skill experience points
 bwoodcutting:
   description: buy McMMO Woodcutting skill experience points
